name: Python Test Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the runner OS (Ubuntu in this case)

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Use a specific Python version (3.8)

    # Install dependencies (optional, if you have dependencies like pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest if it's not installed

    # Run all tests in the repository
    - name: Run tests
      run: |
        python -m pytest  # This will run all tests that pytest can find in the repo
